### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by kirajok** [Cybertat1on/Qlyuker#1]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\1KLYKER\Qlyuker\bot\core\tapper.py", line 292, in check_proxy
    logger.info(f"<cyan>{self.session_name}</cyan> | Proxy IP: <green>{ip}<>/green>")
  File "C:\Users\Administrator\Desktop\1KLYKER\Qlyuker\venv\Lib\site-packages\loguru\_logger.py", line 2044, in info
    __self._log("INFO", False, __self._options, __message, args, kwargs)
  File "C:\Users\Administrator\Desktop\1KLYKER\Qlyuker\venv\Lib\site-packages\loguru\_logger.py", line 2017, in _log
    colored_message = Colorizer.prepare_simple_message(str(message))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\1KLYKER\Qlyuker\venv\Lib\site-packages\loguru\_colorizer.py", line 368, in prepare_simple_message
    parser.feed(string)
  File "C:\Users\Administrator\Desktop\1KLYKER\Qlyuker\venv\Lib\site-packages\loguru\_colorizer.py", line 252, in feed
    raise ValueError(
ValueError: Tag "<>" does not correspond to any known color directive, make sure you did not misspelled it (or prepend '\' to escape it)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\1KLYKER\Qlyuker\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\1KLYKER\Qlyuker\main.py", line 8, in main
    await process()
  File "C:\Users\Administrator\Desktop\1KLYKER\Qlyuker\bot\utils\launcher.py", line 103, in process
    await run_tasks(tg_clients=tg_clients)
  File "C:\Users\Administrator\Desktop\1KLYKER\Qlyuker\bot\utils\launcher.py", line 117, in run_tasks
    await asyncio.gather(*tasks)
  File "C:\Users\Administrator\Desktop\1KLYKER\Qlyuker\bot\core\tapper.py", line 395, in run_tapper
    await Tapper(tg_client=tg_client).run(proxy=proxy)
  File "C:\Users\Administrator\Desktop\1KLYKER\Qlyuker\bot\core\tapper.py", line 301, in run
    await self.check_proxy(http_client=http_client, proxy=proxy)
  File "C:\Users\Administrator\Desktop\1KLYKER\Qlyuker\bot\core\tapper.py", line 294, in check_proxy
    logger.error(f"<cyan>{self.session_name}</cyan> | Proxy: {proxy} | Error: {error}")
  File "C:\Users\Administrator\Desktop\1KLYKER\Qlyuker\venv\Lib\site-packages\loguru\_logger.py", line 2056, in error
    __self._log("ERROR", False, __self._options, __message, args, kwargs)
  File "C:\Users\Administrator\Desktop\1KLYKER\Qlyuker\venv\Lib\site-packages\loguru\_logger.py", line 2017, in _log
    colored_message = Colorizer.prepare_simple_message(str(message))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\1KLYKER\Qlyuker\venv\Lib\site-packages\loguru\_colorizer.py", line 368, in prepare_simple_message
    parser.feed(string)
  File "C:\Users\Administrator\Desktop\1KLYKER\Qlyuker\venv\Lib\site-packages\loguru\_colorizer.py", line 252, in feed
    raise ValueError(
ValueError: Tag "<>" does not correspond to any known color directive, make sure you did not misspelled it (or prepend '\' to escape it)
done
PLEASE EDIT .ENV FILE

**Comment by Cybertat1on** [comment]
Fix, use git pull

**Comment by kirajok** [comment]
Good job thx
