### ISSUE TITLE
No module named 'loguru'

### ISSUE THREAD

**Issue by EvelRus** [Cybertat1on/Qlyuker#2]
Очень странно, модуль установлен, но пишет, что его нет (

(venv) user@MacBook-Pro Qlyuker % python3 main.py
Traceback (most recent call last):
  File "/Users/user/Downloads/Qlyuker/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/Users/user/Downloads/Qlyuker/bot/utils/__init__.py", line 1, in <module>
    from .logger import logger
  File "/Users/user/Downloads/Qlyuker/bot/utils/logger.py", line 2, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

(venv) user@MacBook-Pro Qlyuker % pip install loguru   
Requirement already satisfied: loguru in ./venv/lib/python3.10/site-packages (0.7.2)

**Comment by EvelRus** [comment]
Помогло только выполнение команд в стиле
/path/to/python3 -m pip install pyrogram

Запустился!

**Comment by Cybertat1on** [comment]
Gj!
Unfortunately I don't have a mac for full testing.
